use std::collections::BTreeMap;
use std::fmt::Write;

use super::{Event, Module, Side};

const HEADER: &str = r#"--!strict
-- Generated by RoGrid. Do not edit.
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Generated = ReplicatedStorage:WaitForChild("RoGridGenerated", 10)
assert(Generated, "RoGrid output is missing; run rogrid dev")
local packages = ReplicatedStorage:WaitForChild("Packages", 10)
assert(packages, "RoGrid packages are missing; install project dependencies")
local library = packages:WaitForChild("rogrid", 10)
assert(library and library:IsA("ModuleScript"), "RoGrid package is missing; install project dependencies")
local RoGrid = require(library)
assert(RoGrid._protocol == 3, "RoGrid CLI and package are incompatible; use matching code and regenerate")
local _rogridRuntime = RoGrid._runtime
local revisionModule = Generated:WaitForChild("Revision", 10)
assert(revisionModule and revisionModule:IsA("ModuleScript"), "RoGrid revision is missing")
"#;

pub fn files(modules: &[Module], revision: &str) -> BTreeMap<String, String> {
    BTreeMap::from([
        (
            "shared/Server.luau".into(),
            callers(modules, Side::Server, revision),
        ),
        (
            "server/Client.luau".into(),
            callers(modules, Side::Client, revision),
        ),
        (
            "server/Start.luau".into(),
            startup(modules, Side::Server, revision),
        ),
        (
            "client/Start.luau".into(),
            startup(modules, Side::Client, revision),
        ),
    ])
}

fn header(revision: &str) -> String {
    format!(
        "{HEADER}local _rogridRevision = \"{revision}\"\nassert(require(revisionModule) == _rogridRevision, \"RoGrid generated files disagree; rerun rogrid dev and restart Play\")\n\n"
    )
}

pub(super) fn id(module: &Module, event: &Event) -> String {
    format!("{}.{}.{}", module.side.name(), module.name, event.name)
}

fn callers(modules: &[Module], destination: Side, revision: &str) -> String {
    let mut code = header(revision);
    writeln!(code, "return {{").unwrap();
    for module in modules.iter().filter(|m| m.side == destination) {
        writeln!(code, "\t{} = {{", module.name).unwrap();
        for event in &module.events {
            writeln!(code, "\t\t{} = {{", event.name).unwrap();
            let arguments = event
                .args
                .iter()
                .map(|a| format!("{}: {}", a.name, a.ty))
                .collect::<Vec<_>>()
                .join(", ");
            let values = event
                .args
                .iter()
                .map(|a| format!(", {}", a.name))
                .collect::<String>();
            let id = id(module, event);
            if destination == Side::Server {
                writeln!(code, "\t\t\tfire = function({arguments}): ()\n\t\t\t\t_rogridRuntime.fireServer(\"{id}\", _rogridRevision{values})\n\t\t\tend,").unwrap();
            } else {
                // Keep the target readable in editor hints without shadowing payload names.
                let mut player = "player".to_string();
                let mut suffix = 2;
                while event.args.iter().any(|arg| arg.name == player) {
                    player = format!("player{suffix}");
                    suffix += 1;
                }
                let targeted_arguments = if arguments.is_empty() {
                    format!("{player}: Player")
                } else {
                    format!("{player}: Player, {arguments}")
                };
                writeln!(code, "\t\t\tfire = function({targeted_arguments}): ()\n\t\t\t\t_rogridRuntime.fireClient(\"{id}\", _rogridRevision, {player}{values})\n\t\t\tend,").unwrap();
                writeln!(code, "\t\t\tfireAll = function({arguments}): ()\n\t\t\t\t_rogridRuntime.fireAllClients(\"{id}\", _rogridRevision{values})\n\t\t\tend,").unwrap();
            }
            writeln!(code, "\t\t}},").unwrap();
        }
        writeln!(code, "\t}},").unwrap();
    }
    writeln!(code, "}}").unwrap();
    code
}

fn startup(modules: &[Module], side: Side, revision: &str) -> String {
    let mut code = header(revision);
    writeln!(code, "return function(): ()").unwrap();
    writeln!(
        code,
        "\t_rogridRuntime.begin(\"{}\", _rogridRevision, {{",
        side.name()
    )
    .unwrap();
    for module in modules {
        for event in &module.events {
            writeln!(code, "\t\t\"{}\",", id(module, event)).unwrap();
        }
    }
    writeln!(code, "\t}})").unwrap();
    for (index, module) in modules.iter().filter(|m| m.side == side).enumerate() {
        writeln!(
            code,
            "\tlocal receiver{index} = _rogridRuntime.load({{ {} }}, {{ {} }})",
            module
                .location
                .iter()
                .map(|name| super::types::quote(name))
                .collect::<Vec<_>>()
                .join(", "),
            module
                .events
                .iter()
                .map(|e| format!("\"{}\"", e.name))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
        for event in &module.events {
            writeln!(
                code,
                "\t_rogridRuntime.bind(\"{}\", receiver{index}.{}, {{",
                id(module, event),
                event.name
            )
            .unwrap();
            for argument in &event.args {
                writeln!(
                    code,
                    "\t\t{{ name = {}, shape = {} }},",
                    super::types::quote(&argument.name),
                    argument.ty.descriptor()
                )
                .unwrap();
            }
            writeln!(code, "\t}})").unwrap();
        }
    }
    writeln!(code, "\t_rogridRuntime.finish()\nend").unwrap();
    code
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{fs, path::Path, process::Command};

    #[test]
    #[ignore = "requires Lune on PATH; executes generated startup and compatibility guards"]
    fn generated_startup_and_compatibility_guards_execute() {
        let modules = vec![
            Module {
                side: Side::Server,
                name: "Tests".into(),
                location: vec!["ServerStorage".into(), "Tests".into()],
                events: vec![Event {
                    name: "receive".into(),
                    args: vec![],
                }],
            },
            Module {
                side: Side::Client,
                name: "Tests".into(),
                location: vec!["PlayerScripts".into(), "Tests".into()],
                events: vec![Event {
                    name: "receive".into(),
                    args: vec![],
                }],
            },
        ];
        let mut generated = files(&modules, "test");
        generated.insert("shared/Revision.luau".into(), "return 'test'\n".into());
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("generated.json");
        fs::write(&path, serde_json::to_string(&generated).unwrap()).unwrap();
        let repo = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let output = Command::new("lune")
            .current_dir(repo)
            .args(["run", "packages/rogrid/tests/generated.luau"])
            .arg(path)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
