use std::collections::BTreeMap;
use std::fmt::Write;

use super::{Endpoint, EndpointKind, Module, Side};

const HEADER: &str = r#"--!strict
-- Generated by RoGrid. Do not edit.
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Generated = ReplicatedStorage:WaitForChild("RoGridGenerated")
local packages = ReplicatedStorage:WaitForChild("Packages")
local library = packages:WaitForChild("rogrid")
assert(library:IsA("ModuleScript"), "RoGrid package must be a ModuleScript; install project dependencies")
local RoGrid = require(library)
assert(RoGrid._protocol == 4, "RoGrid CLI and package are incompatible; use matching code and regenerate")
local _rogridRuntime = RoGrid._runtime
local revisionModule = Generated:WaitForChild("Revision")
assert(revisionModule:IsA("ModuleScript"), "RoGrid revision must be a ModuleScript")
"#;

pub fn files(modules: &[Module], revision: &str) -> BTreeMap<String, String> {
    BTreeMap::from([
        (
            "shared/Server.luau".into(),
            callers(modules, Side::Server, revision),
        ),
        (
            "server/Client.luau".into(),
            callers(modules, Side::Client, revision),
        ),
        (
            "shared/Definitions.luau".into(),
            definitions(modules, revision),
        ),
        (
            "server/Start.luau".into(),
            startup(modules, Side::Server, revision),
        ),
        (
            "client/Start.luau".into(),
            startup(modules, Side::Client, revision),
        ),
    ])
}

fn header(revision: &str) -> String {
    format!(
        "{HEADER}local _rogridRevision = \"{revision}\"\nassert(require(revisionModule) == _rogridRevision, \"RoGrid generated files disagree; rerun rogrid dev and restart Play\")\n\n"
    )
}

pub(super) fn id(module: &Module, endpoint: &Endpoint) -> String {
    format!("{}.{}.{}", module.side.name(), module.name, endpoint.name)
}

pub(super) fn returns(types: &[super::types::NetworkPayloadType]) -> String {
    format!(
        "({})",
        types
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn argument_name(endpoint: &Endpoint, preferred: &str) -> String {
    let mut name = preferred.to_string();
    let mut suffix = 2;
    while endpoint.args.iter().any(|arg| arg.name == name) {
        name = format!("{preferred}{suffix}");
        suffix += 1;
    }
    name
}

fn callers(modules: &[Module], destination: Side, revision: &str) -> String {
    let mut code = header(revision);
    writeln!(code, "return {{").unwrap();
    for module in modules.iter().filter(|m| m.side == destination) {
        writeln!(code, "\t{} = {{", module.name).unwrap();
        for endpoint in &module.endpoints {
            writeln!(code, "\t\t{} = {{", endpoint.name).unwrap();
            let arguments = endpoint
                .args
                .iter()
                .map(|a| format!("{}: {}", a.name, a.ty))
                .collect::<Vec<_>>()
                .join(", ");
            let values = endpoint
                .args
                .iter()
                .map(|a| format!(", {}", a.name))
                .collect::<String>();
            let id = id(module, endpoint);
            match &endpoint.kind {
                EndpointKind::Request(result) => {
                    let timeout = argument_name(endpoint, "timeoutSeconds");
                    let args = if arguments.is_empty() {
                        format!("{timeout}: number?")
                    } else {
                        format!("{arguments}, {timeout}: number?")
                    };
                    writeln!(code, "\t\t\tinvoke = function({args}): {}\n\t\t\t\treturn _rogridRuntime.invokeServer(\"{id}\", _rogridRevision, {timeout}{values})\n\t\t\tend,", returns(result)).unwrap();
                }
                EndpointKind::Event(_) if destination == Side::Server => {
                    writeln!(code, "\t\t\tfire = function({arguments}): ()\n\t\t\t\t_rogridRuntime.fireServer(\"{id}\", _rogridRevision{values})\n\t\t\tend,").unwrap();
                }
                EndpointKind::Event(_) => {
                    let player = argument_name(endpoint, "player");
                    let args = if arguments.is_empty() {
                        format!("{player}: Player")
                    } else {
                        format!("{player}: Player, {arguments}")
                    };
                    writeln!(code, "\t\t\tfire = function({args}): ()\n\t\t\t\t_rogridRuntime.fireClient(\"{id}\", _rogridRevision, {player}{values})\n\t\t\tend,").unwrap();
                    writeln!(code, "\t\t\tfireAll = function({arguments}): ()\n\t\t\t\t_rogridRuntime.fireAllClients(\"{id}\", _rogridRevision{values})\n\t\t\tend,").unwrap();
                }
            }
            writeln!(code, "\t\t}},").unwrap();
        }
        writeln!(code, "\t}},").unwrap();
    }
    writeln!(code, "}}").unwrap();
    code
}

fn definitions(modules: &[Module], revision: &str) -> String {
    let mut code = header(revision);
    writeln!(code, "local definitions: {{ RoGrid._Definition }} = {{").unwrap();
    for module in modules {
        for endpoint in &module.endpoints {
            writeln!(
                code,
                "\t{{ id = \"{}\", receiver = \"{}\",",
                id(module, endpoint),
                module.side.name()
            )
            .unwrap();
            match &endpoint.kind {
                EndpointKind::Event(reliability) => writeln!(
                    code,
                    "\t\tkind = \"event\", reliability = \"{}\",",
                    reliability.name()
                )
                .unwrap(),
                EndpointKind::Request(result) => {
                    writeln!(code, "\t\tkind = \"request\", returns = {{").unwrap();
                    for (index, ty) in result.iter().enumerate() {
                        writeln!(
                            code,
                            "\t\t\t{{ name = \"returns[{}]\", shape = {} }},",
                            index + 1,
                            ty.descriptor()
                        )
                        .unwrap();
                    }
                    writeln!(code, "\t\t}},").unwrap();
                }
            }
            writeln!(code, "\t\targuments = {{").unwrap();
            for argument in &endpoint.args {
                writeln!(
                    code,
                    "\t\t\t{{ name = {}, shape = {} }},",
                    super::types::quote(&argument.name),
                    argument.ty.descriptor()
                )
                .unwrap();
            }
            writeln!(code, "\t\t}},\n\t}},").unwrap();
        }
    }
    writeln!(code, "}}\nreturn definitions").unwrap();
    code
}

fn startup(modules: &[Module], side: Side, revision: &str) -> String {
    let mut code = header(revision);
    writeln!(code, "local definitions = Generated:WaitForChild(\"Definitions\")\nassert(definitions:IsA(\"ModuleScript\"), \"RoGrid definitions must be a ModuleScript\")\n").unwrap();
    writeln!(code, "return function(): ()\n\t_rogridRuntime.begin(\"{}\", _rogridRevision, require(definitions))", side.name()).unwrap();
    for (index, module) in modules.iter().filter(|m| m.side == side).enumerate() {
        writeln!(
            code,
            "\tlocal receiver{index} = _rogridRuntime.load({{ {} }}, {{ {} }})",
            module
                .location
                .iter()
                .map(|name| super::types::quote(name))
                .collect::<Vec<_>>()
                .join(", "),
            module
                .endpoints
                .iter()
                .map(|e| format!("\"{}\"", e.name))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .unwrap();
        for endpoint in &module.endpoints {
            writeln!(
                code,
                "\t_rogridRuntime.bind(\"{}\", receiver{index}.{})",
                id(module, endpoint),
                endpoint.name
            )
            .unwrap();
        }
    }
    writeln!(code, "\t_rogridRuntime.finish()\nend").unwrap();
    code
}

#[cfg(test)]
mod tests {
    use super::super::Reliability;
    use super::super::{
        Argument,
        types::{Leaf, NetworkPayloadType},
    };
    use super::*;
    use std::{fs, path::Path, process::Command};

    #[test]
    #[ignore = "requires Lune on PATH; executes generated startup and compatibility guards"]
    fn generated_startup_and_compatibility_guards_execute() {
        let mut modules = vec![
            Module {
                side: Side::Server,
                name: "Tests".into(),
                location: vec!["ServerStorage".into(), "Tests".into()],
                endpoints: vec![Endpoint {
                    kind: EndpointKind::Event(Reliability::Reliable),
                    name: "receive".into(),
                    args: vec![],
                }],
            },
            Module {
                side: Side::Client,
                name: "Tests".into(),
                location: vec!["PlayerScripts".into(), "Tests".into()],
                endpoints: vec![Endpoint {
                    kind: EndpointKind::Event(Reliability::Reliable),
                    name: "receive".into(),
                    args: vec![],
                }],
            },
        ];
        modules[0].endpoints.push(Endpoint {
            name: "read".into(),
            args: vec![
                Argument {
                    name: "value".into(),
                    ty: NetworkPayloadType::Leaf(Leaf::Number),
                },
                Argument {
                    name: "note".into(),
                    ty: NetworkPayloadType::Leaf(Leaf::String).optional(),
                },
            ],
            kind: EndpointKind::Request(vec![
                NetworkPayloadType::Leaf(Leaf::Number),
                NetworkPayloadType::Leaf(Leaf::String).optional(),
            ]),
        });
        for module in &mut modules {
            module.endpoints.push(Endpoint {
                name: "pose".into(),
                args: vec![Argument {
                    name: "value".into(),
                    ty: NetworkPayloadType::Leaf(Leaf::Number),
                }],
                kind: EndpointKind::Event(Reliability::Unreliable),
            });
            module.endpoints.push(Endpoint {
                kind: EndpointKind::Event(Reliability::Reliable),
                name: "many".into(),
                args: (1..=32)
                    .map(|i| Argument {
                        name: format!("p{i}"),
                        ty: NetworkPayloadType::Leaf(Leaf::Number),
                    })
                    .collect(),
            });
            let mut nested = NetworkPayloadType::Leaf(Leaf::Number);
            for _ in 0..128 {
                nested = NetworkPayloadType::Record(vec![Argument {
                    name: "child".into(),
                    ty: nested,
                }]);
            }
            module.endpoints.push(Endpoint {
                kind: EndpointKind::Event(Reliability::Reliable),
                name: "deep".into(),
                args: vec![Argument {
                    name: "value".into(),
                    ty: nested,
                }],
            });
            module.endpoints.push(Endpoint {
                kind: EndpointKind::Event(Reliability::Reliable),
                name: "wide".into(),
                args: vec![Argument {
                    name: "value".into(),
                    ty: NetworkPayloadType::Record(
                        (1..=5000)
                            .map(|i| Argument {
                                name: format!("f{i}"),
                                ty: NetworkPayloadType::Leaf(Leaf::Number),
                            })
                            .collect(),
                    ),
                }],
            });
        }
        let mut generated = files(&modules, "test");
        generated.insert("shared/Revision.luau".into(), "return 'test'\n".into());
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("generated.json");
        fs::write(&path, serde_json::to_string(&generated).unwrap()).unwrap();
        let repo = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let output = Command::new("lune")
            .current_dir(repo)
            .args(["run", "packages/rogrid/tests/generated.luau"])
            .arg(path)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
