pub mod config;
mod discover;
mod emit;
mod parse;
mod report;
mod resolve;
mod sourcemap;
mod types;

pub use report::Report;

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};

const OUTPUT: &str = ".rogrid/generated";
const INVALID: &str = "--!strict\nerror(\"RoGrid generation is incomplete. Run rogrid dev and fix the reported errors before starting Play.\")\nreturn \"invalid\"\n";

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Side {
    Server,
    Client,
}

impl Side {
    fn name(self) -> &'static str {
        match self {
            Self::Server => "server",
            Self::Client => "client",
        }
    }
}

use types::Field as Argument;

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Reliability {
    Reliable,
    Unreliable,
}

impl Reliability {
    fn name(self) -> &'static str {
        match self {
            Self::Reliable => "reliable",
            Self::Unreliable => "unreliable",
        }
    }
}

pub enum EndpointKind {
    Event(Reliability),
    Request(Vec<types::NetworkPayloadType>),
}

pub struct Endpoint {
    name: String,
    args: Vec<Argument>,
    kind: EndpointKind,
}

pub struct Module {
    side: Side,
    name: String,
    endpoints: Vec<Endpoint>,
    location: Vec<String>,
}

/// Regenerates from source, never executes game code. Failed generation blocks
/// the next startup instead of leaving apparently usable, stale interfaces.
pub fn generate(root: &Path, path_first: &[PathBuf]) -> Result<Report> {
    match generate_inner(root, path_first) {
        Ok(report) => Ok(report),
        Err(error) => {
            invalidate(root)?;
            Err(error)
        }
    }
}

pub fn invalidate(root: &Path) -> Result<()> {
    write_changed(&root.join(OUTPUT).join("shared/Revision.luau"), INVALID)
        .context("could not invalidate stale generated code")
}

/// Rojo needs these directories even before the first successful generation.
pub fn prepare(root: &Path) -> Result<()> {
    configure(root)?;
    for side in ["shared", "server", "client"] {
        fs::create_dir_all(root.join(OUTPUT).join(side))?;
    }
    Ok(())
}

fn generate_inner(root: &Path, path_first: &[PathBuf]) -> Result<Report> {
    let mut digest = Sha256::new();
    digest.update(b"rogrid-endpoints-v1\0");
    digest.update(include_str!("emit.rs"));
    digest.update(include_str!("types.rs"));
    digest.update(include_str!("resolve.rs"));
    digest.update(include_str!("parse.rs"));
    let config = config::load(root)?;
    config.validate_folders(root)?;
    prepare(root)?;
    let map = sourcemap::read(root, path_first)?;
    let modules = discover::modules(root, &config, &map, &mut digest)?;
    // Reporting metadata stays outside the generated Rojo trees. A missing or
    // unreadable cache simply lists all current endpoints as new.
    let inventory_path = root.join(".rogrid/endpoints.json");
    let previous: report::Inventory = fs::read_to_string(&inventory_path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .unwrap_or_default();
    let current = report::inventory(&modules);
    let revision = format!("{:x}", digest.finalize());
    let mut files = emit::files(&modules, &revision);
    let revision_path = root.join(OUTPUT).join("shared/Revision.luau");
    let valid = format!("--!strict\n-- Generated by RoGrid. Do not edit.\nreturn \"{revision}\"\n");
    // Invalidate before changing a generation, then publish its revision last.
    if files.iter().any(|(name, text)| {
        fs::read_to_string(root.join(OUTPUT).join(name))
            .ok()
            .as_deref()
            != Some(text)
    }) {
        write_changed(&revision_path, INVALID)?;
    }
    for (name, contents) in &files {
        write_changed(&root.join(OUTPUT).join(name), contents)?;
    }
    files.insert("shared/Revision.luau".into(), valid.clone());
    remove_obsolete(&root.join(OUTPUT), &root.join(OUTPUT), &files)?;
    write_changed(&revision_path, &valid)?;
    write_changed(
        &inventory_path,
        &(serde_json::to_string_pretty(&current)? + "\n"),
    )?;
    Ok(Report::between(&previous, &current))
}

fn identifier(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        && ![
            "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "if", "in",
            "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while",
        ]
        .contains(&name)
}

fn write_changed(path: &Path, contents: &str) -> Result<()> {
    if fs::read_to_string(path).ok().as_deref() == Some(contents) {
        return Ok(());
    }
    fs::create_dir_all(path.parent().context("output has no parent")?)?;
    fs::write(path, contents).with_context(|| format!("could not write {}", path.display()))
}

fn remove_obsolete(root: &Path, dir: &Path, files: &BTreeMap<String, String>) -> Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            remove_obsolete(root, &path, files)?;
            if fs::read_dir(&path)?.next().is_none() {
                fs::remove_dir(path)?;
            }
        } else {
            let relative = path
                .strip_prefix(root)?
                .to_string_lossy()
                .replace('\\', "/");
            if !files.contains_key(&relative) {
                fs::remove_file(path)?;
            }
        }
    }
    Ok(())
}

/// Add only RoGrid's mappings/settings; preserve the user's other project data.
pub fn configure(root: &Path) -> Result<()> {
    let project_path = root.join("default.project.json");
    let mut project: Value = serde_json::from_str(
        &fs::read_to_string(&project_path)
            .context("run this command in a RoGrid project containing default.project.json")?,
    )?;
    let mut changed = false;
    for (parent, path) in [
        ("/tree/ReplicatedStorage", ".rogrid/generated/shared"),
        ("/tree/ServerScriptService", ".rogrid/generated/server"),
        (
            "/tree/StarterPlayer/StarterPlayerScripts",
            ".rogrid/generated/client",
        ),
    ] {
        let node = project
            .pointer_mut(parent)
            .and_then(Value::as_object_mut)
            .with_context(|| format!("default.project.json needs an object at {parent}"))?;
        let expected = json!({"$path": path});
        if let Some(existing) = node.get("RoGridGenerated") {
            if existing != &expected {
                bail!("{parent}/RoGridGenerated already has a different mapping");
            }
        } else {
            node.insert("RoGridGenerated".into(), expected);
            changed = true;
        }
    }
    if changed {
        write_changed(
            &project_path,
            &(serde_json::to_string_pretty(&project)? + "\n"),
        )?;
    }
    let settings_path = root.join(".vscode/settings.json");
    // Existing VS Code files may use JSONC. Preserve user-owned settings.
    if settings_path.exists() {
        return Ok(());
    }
    let mut settings = json!({});
    let settings = settings
        .as_object_mut()
        .context("VS Code settings must be a JSON object")?;
    for (key, value) in [
        ("luau-lsp.platform.type", json!("roblox")),
        ("luau-lsp.sourcemap.enabled", json!(true)),
        ("luau-lsp.sourcemap.autogenerate", json!(true)),
        (
            "luau-lsp.sourcemap.rojoProjectFile",
            json!("default.project.json"),
        ),
        ("luau-lsp.diagnostics.strictDatamodelTypes", json!(true)),
    ] {
        settings.entry(key).or_insert(value);
    }
    write_changed(
        &settings_path,
        &(serde_json::to_string_pretty(settings)? + "\n"),
    )?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project() -> (tempfile::TempDir, Value) {
        let dir = tempfile::tempdir().unwrap();
        let project = json!({"name": "custom", "servePort": 9876, "tree": {
            "$className": "DataModel",
            "ReplicatedStorage": {"Shared": {"$path": "shared"}},
            "ServerScriptService": {"$ignoreUnknownInstances": true},
            "StarterPlayer": {"StarterPlayerScripts": {"$path": "client"}}
        }});
        fs::write(
            dir.path().join("default.project.json"),
            serde_json::to_string(&project).unwrap(),
        )
        .unwrap();
        (dir, project)
    }

    #[test]
    fn configuration_adds_only_generated_mappings_and_preserves_editor_jsonc() {
        let (dir, original) = project();
        fs::create_dir(dir.path().join(".vscode")).unwrap();
        let settings = "{ // user settings\n\"editor.tabSize\": 2,\n}\n";
        fs::write(dir.path().join(".vscode/settings.json"), settings).unwrap();
        configure(dir.path()).unwrap();
        let mut updated: Value = serde_json::from_str(
            &fs::read_to_string(dir.path().join("default.project.json")).unwrap(),
        )
        .unwrap();
        for parent in [
            "/tree/ReplicatedStorage",
            "/tree/ServerScriptService",
            "/tree/StarterPlayer/StarterPlayerScripts",
        ] {
            assert!(
                updated
                    .pointer_mut(parent)
                    .unwrap()
                    .as_object_mut()
                    .unwrap()
                    .remove("RoGridGenerated")
                    .is_some()
            );
        }
        assert_eq!(updated, original);
        assert_eq!(
            fs::read_to_string(dir.path().join(".vscode/settings.json")).unwrap(),
            settings
        );
        let before = fs::read(dir.path().join("default.project.json")).unwrap();
        configure(dir.path()).unwrap();
        assert_eq!(
            fs::read(dir.path().join("default.project.json")).unwrap(),
            before
        );
    }

    #[test]
    fn configuration_refuses_conflicting_mappings_or_missing_service_nodes_without_writes() {
        for pointer in [
            "/tree/ReplicatedStorage",
            "/tree/ServerScriptService",
            "/tree/StarterPlayer/StarterPlayerScripts",
        ] {
            for replacement in [
                json!({"RoGridGenerated": {"$path": "my-files"}}),
                json!(null),
            ] {
                let (dir, mut original) = project();
                *original.pointer_mut(pointer).unwrap() = replacement;
                let source = serde_json::to_string(&original).unwrap();
                fs::write(dir.path().join("default.project.json"), &source).unwrap();
                assert!(configure(dir.path()).is_err());
                assert_eq!(
                    fs::read_to_string(dir.path().join("default.project.json")).unwrap(),
                    source
                );
                assert!(!dir.path().join(".vscode").exists());
            }
        }
    }

    #[test]
    fn missing_editor_settings_receive_documented_defaults() {
        let (dir, _) = project();
        prepare(dir.path()).unwrap();
        let settings: Value = serde_json::from_str(
            &fs::read_to_string(dir.path().join(".vscode/settings.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(settings["luau-lsp.platform.type"], "roblox");
        assert_eq!(
            settings["luau-lsp.sourcemap.rojoProjectFile"],
            "default.project.json"
        );
        for side in ["shared", "server", "client"] {
            assert!(dir.path().join(OUTPUT).join(side).is_dir());
        }
    }
}
